// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIr7YIHf2PjR5Ey-342kBzp3e2lrZl_Gk',
    appId: '1:522123459411:android:8dd425b65b4be95ab73fa6',
    messagingSenderId: '522123459411',
    projectId: 'socially-89fbf',
    storageBucket: 'socially-89fbf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsWDXsT_pQkqWQ67i7SzeOPoR1hgg2yAw',
    appId: '1:522123459411:ios:ecf628da51af454cb73fa6',
    messagingSenderId: '522123459411',
    projectId: 'socially-89fbf',
    storageBucket: 'socially-89fbf.firebasestorage.app',
    iosBundleId: 'com.example.socially',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYJ_r8EnyB7-FGM-nd1Kpe-AibyRkbdZQ',
    appId: '1:522123459411:web:7b76b77acf1efa06b73fa6',
    messagingSenderId: '522123459411',
    projectId: 'socially-89fbf',
    authDomain: 'socially-89fbf.firebaseapp.com',
    storageBucket: 'socially-89fbf.firebasestorage.app',
  );
}
